[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
env =
    SUPABASE_URL=test_url
    SUPABASE_ANON_KEY=test_key

